ra_sr_ur_robot_hw:
  type: sr_ur_robot_hw/UrArmRobotHW

  # ra for right side arm la for left side arm
  robot_id: ra

  # for sending robot programs
  robot_ip_address: 192.168.1.1

  # for the server that moves the robot
  control_pc_ip_address: 192.168.1.100

ra_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ra_shoulder_pan_joint
    - ra_shoulder_lift_joint
    - ra_elbow_joint
    - ra_wrist_1_joint
    - ra_wrist_2_joint
    - ra_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ra_shoulder_pan_joint: {trajectory: 0.3, goal: 0.1}
      ra_shoulder_lift_joint: {trajectory: 0.3, goal: 0.1}
      ra_elbow_joint: {trajectory: 0.3, goal: 0.1}
      ra_wrist_1_joint: {trajectory: 0.3, goal: 0.1}
      ra_wrist_2_joint: {trajectory: 0.3, goal: 0.1}
      ra_wrist_3_joint: {trajectory: 0.3, goal: 0.1}
  stop_trajectory_duration: 0.5
  allow_partial_joints_goal: true
